In [3]:
import pandas as pa
import numpy as np
from sklearn.preprocessing import MinMaxScaler 

In [4]:
names = ['height','weight'] 

dataframe =pa.read_csv(r"C:\Users\riyam\OneDrive - vit.ac.in\SEMESTER 5\AI\LAB\EXPERIMENT 1\data.csv", names=names) 
dataframe.head() 

height  weight
0     5.5   51251
1     6.0   61911
2     5.8   69413
3     5.7   64564
4     5.6   65453

In [5]:
array = dataframe.values 
array

array([[5.5000e+00, 5.1251e+04],
       [6.0000e+00, 6.1911e+04],
       [5.8000e+00, 6.9413e+04],
       [5.7000e+00, 6.4564e+04],
       [5.6000e+00, 6.5453e+04],
       [5.7000e+00, 5.5928e+04],
       [5.8000e+00, 6.4179e+04],
       [5.8000e+00, 6.1897e+04],
       [5.7000e+00, 5.0970e+04],
       [5.6000e+00, 5.4735e+04],
       [5.5000e+00, 5.7810e+04],
       [5.6000e+00, 5.1773e+04],
       [5.7000e+00, 5.6976e+04],
       [5.6000e+00, 5.5547e+04],
       [5.7000e+00, 5.2658e+04],
       [5.9000e+00, 6.3503e+04],
       [5.5000e+00, 5.8740e+04],
       [5.7000e+00, 6.4850e+04],
       [5.9000e+00, 6.2550e+04],
       [5.6000e+00, 5.6264e+04],
       [5.7000e+00, 6.4084e+04],
       [5.7000e+00, 6.5109e+04],
       [5.3000e+00, 4.4407e+04],
       [5.7000e+00, 5.8740e+04],
       [5.6000e+00, 6.4342e+04],
       [5.6000e+00, 5.8840e+04],
       [5.9000e+00, 6.4601e+04],
       [5.6000e+00, 5.9670e+04],
       [5.5000e+00, 4.9138e+04],
       [5.5000e+00, 5.1660e+04],
       [5.

In [6]:
X = array[:,:-1] 
X

array([[5.5],
       [6. ],
       [5.8],
       [5.7],
       [5.6],
       [5.7],
       [5.8],
       [5.8],
       [5.7],
       [5.6],
       [5.5],
       [5.6],
       [5.7],
       [5.6],
       [5.7],
       [5.9],
       [5.5],
       [5.7],
       [5.9],
       [5.6],
       [5.7],
       [5.7],
       [5.3],
       [5.7],
       [5.6],
       [5.6],
       [5.9],
       [5.6],
       [5.5],
       [5.5],
       [5.8],
       [5.5],
       [5.7],
       [5.9],
       [6. ],
       [5.8],
       [5.6],
       [5.6],
       [5.7],
       [5.3],
       [5.7],
       [5.4],
       [5.8],
       [5.7],
       [5.5],
       [5.7],
       [5.6],
       [5.6],
       [5.8],
       [5.8]])

In [7]:
Y = array[:,-1] 
Y

array([51251., 61911., 69413., 64564., 65453., 55928., 64179., 61897.,
       50970., 54735., 57810., 51773., 56976., 55547., 52658., 63503.,
       58740., 64850., 62550., 56264., 64084., 65109., 44407., 58740.,
       64342., 58840., 64601., 59670., 49138., 51660., 46856., 54771.,
       57057., 61788., 63548., 58400., 64319., 54989., 59579., 48403.,
       56409., 56636., 63353., 62310., 48285., 58405., 66079., 52989.,
       65145., 61203.])

In [8]:
min= MinMaxScaler(feature_range=(-1, 1)) 
scal= min.fit_transform(X)
#rescaledX=scal.transform(X) 

In [11]:
np.set_printoptions(precision=3) 
print(scal[0:5,:])

[[-0.429]
 [ 1.   ]
 [ 0.429]
 [ 0.143]
 [-0.143]]
